name: Run Temperature Data Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r script/requirements.txt

    # Step 4: Run the script
    - name: Run temperature script
      run: |
        python script/main.py

    # Step 5: Archive the output (map file)
    - name: Upload temperature map
      uses: actions/upload-artifact@v3
      with:
        name: temperature-map
        path: output/temperature_map.html
